# 1. Loading and normalizing CIFAR10

In [1]:
import torch
import torchvision
import torchvision.transforms as transforms

In [2]:
x = torch.Tensor(5, 3)
print(x)


-5.7565e+35  4.5744e-41  1.3694e-37
 0.0000e+00 -2.6810e+36  4.5744e-41
-2.5502e+36  4.5744e-41 -5.6608e+19
 4.5744e-41 -1.5530e+33  4.5744e-41
-1.5476e+33  4.5744e-41 -2.0183e-19
[torch.FloatTensor of size 5x3]



In [3]:
x = torch.rand(5, 3)
print(x)


 0.1793  0.3959  0.3042
 0.2055  0.7924  0.5644
 0.4547  0.7810  0.8931
 0.1041  0.6117  0.6522
 0.1413  0.0529  0.1620
[torch.FloatTensor of size 5x3]



In [4]:
print(x.size())

torch.Size([5, 3])


In [5]:
y = torch.rand(5, 3)
print(x + y)


 1.0853  1.0534  1.2578
 0.7139  0.8232  1.2066
 1.4537  1.2090  1.2265
 0.1221  0.6607  1.3565
 0.9426  0.4201  0.7785
[torch.FloatTensor of size 5x3]



In [6]:
print(torch.add(x, y))


 1.0853  1.0534  1.2578
 0.7139  0.8232  1.2066
 1.4537  1.2090  1.2265
 0.1221  0.6607  1.3565
 0.9426  0.4201  0.7785
[torch.FloatTensor of size 5x3]



In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.0853  1.0534  1.2578
 0.7139  0.8232  1.2066
 1.4537  1.2090  1.2265
 0.1221  0.6607  1.3565
 0.9426  0.4201  0.7785
[torch.FloatTensor of size 5x3]



In [8]:
y.add_(x)
print(y)


 1.0853  1.0534  1.2578
 0.7139  0.8232  1.2066
 1.4537  1.2090  1.2265
 0.1221  0.6607  1.3565
 0.9426  0.4201  0.7785
[torch.FloatTensor of size 5x3]



In [9]:
print(x[:, 1])


 0.3959
 0.7924
 0.7810
 0.6117
 0.0529
[torch.FloatTensor of size 5]



In [10]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [11]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [12]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [14]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

In [16]:
import torch
from torch.autograd import Variable
x = Variable(torch.ones(2, 2), requires_grad=True)
print(x)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [17]:
y = x + 2
print(y)

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [18]:
print(y.grad_fn)

In [19]:
z = y * y * 3
out = z.mean()

print(z, out)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



In [20]:
out.backward()

In [21]:
print(x.grad)

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]

